# Generated by Django 5.1.3 on 2024-11-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmgenre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filmgenre',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmgenre',
            name='genre',
        ),
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(to='main.film'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.DeleteModel(
            name='ActorFilm',
        ),
        migrations.DeleteModel(
            name='FilmGenre',
        ),
    ]
