# Generated by Django 5.1.3 on 2024-11-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_filmgenre_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='fulldescr',
            field=models.TextField(default='', verbose_name='полное описание фильма'),
        ),
    ]
