# Generated by Django 5.1.3 on 2024-11-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_film_fulldescr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='fulldescr',
        ),
    ]
