# Generated by Django 5.1.3 on 2024-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_film_fulldescr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='main.actor', verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='main.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='жанр'),
        ),
    ]
