# Generated by Django 5.1.3 on 2024-11-14 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_actor_films_film_actors_alter_film_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='рейтинг'),
        ),
    ]
