# Generated by Django 5.1.3 on 2024-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='трейлер'),
        ),
    ]
