# Generated by Django 5.1.3 on 2024-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
    ]
